# Generated by Django 5.0.4 on 2024-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
