# Generated by Django 5.0.4 on 2024-04-22 02:52

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "foods")

class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_calories'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]



    