# Generated by Django 5.1.2 on 2024-11-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
    ]
