# Generated by Django 5.0.4 on 2024-04-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20240422_0252'),
        ('user_auth', '0002_rename_favorite_food_userprofile_favfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favfood',
            field=models.ManyToManyField(related_name='favfood', to='foods.food'),
        ),
    ]
