# Generated by Django 4.2.5 on 2024-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_alter_drink_category_alter_drink_description_and_more'),
        ('user_auth', '0003_alter_userprofile_favfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favdrink',
            field=models.ManyToManyField(related_name='favdrink', to='drinks.drink'),
        ),
    ]
