# Generated by Django 5.0.4 on 2024-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.TextField(blank=True, null=True)),
                ('merchant_area', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('display', models.TextField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('isDiscount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
