# Generated by Django 3.2.7 on 2024-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Merchant_area', models.CharField(max_length=255)),
                ('Product_name', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('coffee', 'Coffee'), ('non_coffee', 'Non Coffee')], max_length=13)),
                ('Product_description', models.CharField(max_length=255)),
                ('Image', models.URLField()),
            ],
        ),
    ]
