# Generated by Django 3.2.7 on 2024-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='Product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='Merchant_area',
            new_name='merchant_area',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='Product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='Image',
        ),
        migrations.AddField(
            model_name='drink',
            name='merchant_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
