# Generated by Django 5.0.4 on 2024-04-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20240422_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('kopi', 'Kopi'), ('non kopi', 'Non kopi')], max_length=13),
        ),
    ]
