# Generated by Django 5.1.3 on 2024-11-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drinks", "0004_alter_drink_category_alter_drink_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="calories",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
