# Generated by Django 4.2.5 on 2024-05-07 11:57

from django.db import migrations, models
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "drinks")


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_drink_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='merchant_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(load_my_initial_data),
    ]
