# Generated by Django 5.0.4 on 2024-04-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favfnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='food',
            new_name='favfood',
        ),
    ]
