# Generated by Django 5.0.4 on 2024-04-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favfnd', '0002_rename_food_favorite_favfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favfood',
            new_name='food',
        ),
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.CharField(default='n/a', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='merchant_area',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='merchant_name',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
    ]
