# Generated by Django 5.0.6 on 2024-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_alter_drink_category_alter_drink_description_and_more'),
        ('favfnd', '0003_rename_favfood_favorite_food_favorite_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='drink',
            field=models.ManyToManyField(to='drinks.drink'),
        ),
    ]
